/*!   GeneXus C# 16_0_7-138086 on 8/25/2020 17:59:56.34
*/
gx.evt.autoSkip = false;
gx.define('wwpbaseobjects.home', false, function () {
   this.ServerClass =  "wwpbaseobjects.home" ;
   this.PackageName =  "GeneXus.Programs" ;
   this.setObjectType("web");
   this.hasEnterEvent = false;
   this.skipOnEnter = false;
   this.autoRefresh = true;
   this.fullAjax = true;
   this.supportAjaxEvents =  true ;
   this.ajaxSecurityToken =  true ;
   this.SetStandaloneVars=function()
   {
      this.AV8HomeSampleData=gx.fn.getControlValue("vHOMESAMPLEDATA") ;
      this.AV8HomeSampleData=gx.fn.getControlValue("vHOMESAMPLEDATA") ;
   };
   this.e13082_client=function()
   {
      return this.executeServerEvent("ENTER", true, arguments[0], false, false);
   };
   this.e14082_client=function()
   {
      return this.executeServerEvent("CANCEL", true, arguments[0], false, false);
   };
   this.GXValidFnc = [];
   var GXValidFnc = this.GXValidFnc ;
   this.GXCtrlIds=[2,3,4,5,6,7,8,9,10,11,12,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,33,35,36,37,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,58,60,61,62,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,83,85,86,87,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,108,110,111,112,115,116,117,118,119,121,123,124,125,126,127,128,131,132,133,134,135,137,138,141,142,143,144,145];
   this.GXLastCtrlId =145;
   this.GridContainer = new gx.grid.grid(this, 2,"WbpLvl2",122,"Grid","Grid","GridContainer",this.CmpContext,this.IsMasterPage,"wwpbaseobjects.home",[],false,1,false,true,0,true,false,false,"CollWWPBaseObjects\HomeSampleData.HomeSampleDataItem",0,"px",0,"px",gx.getMessage( "GXM_newrow"),true,false,false,null,null,false,"AV8HomeSampleData",false,[1,1,1,1],false,0,true,false);
   var GridContainer = this.GridContainer;
   GridContainer.addSingleLineEdit("GXV2",123,"HOMESAMPLEDATA__PRODUCTNAME",gx.getMessage( "Name"),"","ProductName","svchar",0,"px",40,40,"left",null,[],"GXV2","GXV2",true,0,false,false,"Attribute",1,"WWColumn");
   GridContainer.addSingleLineEdit("GXV3",124,"HOMESAMPLEDATA__PRODUCTPRICE",gx.getMessage( "Price"),"","ProductPrice","decimal",0,"px",11,11,"right",null,[],"GXV3","GXV3",true,1,false,false,"Attribute",1,"WWColumn");
   GridContainer.addComboBox("GXV4",125,"HOMESAMPLEDATA__PRODUCTSTATUS",gx.getMessage( "Status"),"ProductStatus","int",null,0,true,false,0,"px","");
   this.GridContainer.emptyText = gx.getMessage( "");
   this.setGrid(GridContainer);
   this.DVPANEL_CARD1Container = gx.uc.getNew(this, 13, 0, "BootstrapPanel", "DVPANEL_CARD1Container", "Dvpanel_card1", "DVPANEL_CARD1");
   var DVPANEL_CARD1Container = this.DVPANEL_CARD1Container;
   DVPANEL_CARD1Container.setProp("Class", "Class", "", "char");
   DVPANEL_CARD1Container.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_CARD1Container.setProp("Width", "Width", "100%", "str");
   DVPANEL_CARD1Container.setProp("Height", "Height", "100", "str");
   DVPANEL_CARD1Container.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_CARD1Container.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_CARD1Container.setProp("Cls", "Cls", "PanelCardIcon_Warning", "str");
   DVPANEL_CARD1Container.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_CARD1Container.setProp("Title", "Title", "<i class=\"fa fa-shopping-cart\"></i>", "str");
   DVPANEL_CARD1Container.setProp("Collapsible", "Collapsible", false, "bool");
   DVPANEL_CARD1Container.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_CARD1Container.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_CARD1Container.setProp("IconPosition", "Iconposition", "right", "str");
   DVPANEL_CARD1Container.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_CARD1Container.setProp("Visible", "Visible", true, "bool");
   DVPANEL_CARD1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_CARD1Container);
   this.DVPANEL_CARD2Container = gx.uc.getNew(this, 38, 27, "BootstrapPanel", "DVPANEL_CARD2Container", "Dvpanel_card2", "DVPANEL_CARD2");
   var DVPANEL_CARD2Container = this.DVPANEL_CARD2Container;
   DVPANEL_CARD2Container.setProp("Class", "Class", "", "char");
   DVPANEL_CARD2Container.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_CARD2Container.setProp("Width", "Width", "100%", "str");
   DVPANEL_CARD2Container.setProp("Height", "Height", "100", "str");
   DVPANEL_CARD2Container.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_CARD2Container.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_CARD2Container.setProp("Cls", "Cls", "PanelCardIcon_Success", "str");
   DVPANEL_CARD2Container.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_CARD2Container.setProp("Title", "Title", "<i class=\"fa fa-university\"></i>", "str");
   DVPANEL_CARD2Container.setProp("Collapsible", "Collapsible", false, "bool");
   DVPANEL_CARD2Container.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_CARD2Container.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_CARD2Container.setProp("IconPosition", "Iconposition", "right", "str");
   DVPANEL_CARD2Container.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_CARD2Container.setProp("Visible", "Visible", true, "bool");
   DVPANEL_CARD2Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_CARD2Container);
   this.DVPANEL_CARD3Container = gx.uc.getNew(this, 63, 27, "BootstrapPanel", "DVPANEL_CARD3Container", "Dvpanel_card3", "DVPANEL_CARD3");
   var DVPANEL_CARD3Container = this.DVPANEL_CARD3Container;
   DVPANEL_CARD3Container.setProp("Class", "Class", "", "char");
   DVPANEL_CARD3Container.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_CARD3Container.setProp("Width", "Width", "100%", "str");
   DVPANEL_CARD3Container.setProp("Height", "Height", "100", "str");
   DVPANEL_CARD3Container.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_CARD3Container.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_CARD3Container.setProp("Cls", "Cls", "PanelCardIcon_Info", "str");
   DVPANEL_CARD3Container.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_CARD3Container.setProp("Title", "Title", "<i class=\"fa fa-user\"></i>", "str");
   DVPANEL_CARD3Container.setProp("Collapsible", "Collapsible", false, "bool");
   DVPANEL_CARD3Container.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_CARD3Container.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_CARD3Container.setProp("IconPosition", "Iconposition", "right", "str");
   DVPANEL_CARD3Container.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_CARD3Container.setProp("Visible", "Visible", true, "bool");
   DVPANEL_CARD3Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_CARD3Container);
   this.DVPANEL_CARD4Container = gx.uc.getNew(this, 88, 27, "BootstrapPanel", "DVPANEL_CARD4Container", "Dvpanel_card4", "DVPANEL_CARD4");
   var DVPANEL_CARD4Container = this.DVPANEL_CARD4Container;
   DVPANEL_CARD4Container.setProp("Class", "Class", "", "char");
   DVPANEL_CARD4Container.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_CARD4Container.setProp("Width", "Width", "100%", "str");
   DVPANEL_CARD4Container.setProp("Height", "Height", "100", "str");
   DVPANEL_CARD4Container.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_CARD4Container.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_CARD4Container.setProp("Cls", "Cls", "PanelCardIcon_BaseColor", "str");
   DVPANEL_CARD4Container.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_CARD4Container.setProp("Title", "Title", "<i class=\"fa fa-chart-bar\"></i>", "str");
   DVPANEL_CARD4Container.setProp("Collapsible", "Collapsible", false, "bool");
   DVPANEL_CARD4Container.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_CARD4Container.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_CARD4Container.setProp("IconPosition", "Iconposition", "right", "str");
   DVPANEL_CARD4Container.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_CARD4Container.setProp("Visible", "Visible", true, "bool");
   DVPANEL_CARD4Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_CARD4Container);
   this.UTCHARTSMOOTHAREAContainer = gx.uc.getNew(this, 120, 27, "QueryViewer", "UTCHARTSMOOTHAREAContainer", "Utchartsmootharea", "UTCHARTSMOOTHAREA");
   var UTCHARTSMOOTHAREAContainer = this.UTCHARTSMOOTHAREAContainer;
   UTCHARTSMOOTHAREAContainer.setProp("Enabled", "Enabled", true, "boolean");
   UTCHARTSMOOTHAREAContainer.setProp("ObjectId", "Objectid", "1", "str");
   UTCHARTSMOOTHAREAContainer.setProp("ObjectType", "Objecttype", "DataProvider", "str");
   UTCHARTSMOOTHAREAContainer.setProp("QueryInfo", "Queryinfo", "", "char");
   UTCHARTSMOOTHAREAContainer.setProp("IsExternalQuery", "Isexternalquery", false, "boolean");
   UTCHARTSMOOTHAREAContainer.setProp("ExternalQueryResult", "Externalqueryresult", "", "char");
   UTCHARTSMOOTHAREAContainer.setProp("ObjectInfo", "Objectinfo", "", "char");
   UTCHARTSMOOTHAREAContainer.addV2CFunction('AV13Axes', "vAXES", 'SetAxes');
   UTCHARTSMOOTHAREAContainer.addC2VFunction(function(UC) { UC.ParentObject.AV13Axes=UC.GetAxes();gx.fn.setControlValue("vAXES",UC.ParentObject.AV13Axes); });
   UTCHARTSMOOTHAREAContainer.setProp("AllowChangeAxesOrder", "Allowchangeaxesorder", false, "bool");
   UTCHARTSMOOTHAREAContainer.addV2CFunction('AV14Parameters', "vPARAMETERS", 'SetParameters');
   UTCHARTSMOOTHAREAContainer.addC2VFunction(function(UC) { UC.ParentObject.AV14Parameters=UC.GetParameters();gx.fn.setControlValue("vPARAMETERS",UC.ParentObject.AV14Parameters); });
   UTCHARTSMOOTHAREAContainer.setProp("ObjectName", "Objectname", "GetHomeSampleData", "str");
   UTCHARTSMOOTHAREAContainer.setProp("Object", "Objectcall", "", "str");
   UTCHARTSMOOTHAREAContainer.setProp("Class", "Class", "QueryViewer", "str");
   UTCHARTSMOOTHAREAContainer.setProp("ShrinkToFit", "Shrinktofit", false, "boolean");
   UTCHARTSMOOTHAREAContainer.setProp("AutoResize", "Autoresize", false, "boolean");
   UTCHARTSMOOTHAREAContainer.setProp("AutoResizeType", "Autoresizetype", "", "char");
   UTCHARTSMOOTHAREAContainer.setProp("Width", "Width", "100%", "str");
   UTCHARTSMOOTHAREAContainer.setProp("Height", "Height", "100%", "str");
   UTCHARTSMOOTHAREAContainer.setProp("Axes Selectors", "Showaxesselectors", "", "char");
   UTCHARTSMOOTHAREAContainer.setProp("FontFamily", "Fontfamily", "", "char");
   UTCHARTSMOOTHAREAContainer.setProp("FontSize", "Fontsize", '', "int");
   UTCHARTSMOOTHAREAContainer.setProp("FontColor", "Fontcolor", '', "int");
   UTCHARTSMOOTHAREAContainer.setProp("AutoRefreshGroup", "Autorefreshgroup", "", "str");
   UTCHARTSMOOTHAREAContainer.setProp("DisableColumnSort", "Disablecolumnsort", false, "boolean");
   UTCHARTSMOOTHAREAContainer.setProp("AllowSelection", "Allowselection", false, "bool");
   UTCHARTSMOOTHAREAContainer.setProp("RememberLayout", "Rememberlayout", true, "bool");
   UTCHARTSMOOTHAREAContainer.setProp("ExportToXML", "Exporttoxml", true, "bool");
   UTCHARTSMOOTHAREAContainer.setProp("ExportToHTML", "Exporttohtml", true, "bool");
   UTCHARTSMOOTHAREAContainer.setProp("ExportToXLS", "Exporttoxls", true, "bool");
   UTCHARTSMOOTHAREAContainer.setProp("ExportToXLSX", "Exporttoxlsx", true, "bool");
   UTCHARTSMOOTHAREAContainer.setProp("ExportToPDF", "Exporttopdf", true, "bool");
   UTCHARTSMOOTHAREAContainer.setProp("Type", "Type", "Chart", "str");
   UTCHARTSMOOTHAREAContainer.setProp("ShowDataAs", "Showdataas", "", "char");
   UTCHARTSMOOTHAREAContainer.setProp("Orientation", "Orientation", "", "char");
   UTCHARTSMOOTHAREAContainer.setProp("IncludeTrend", "Includetrend", false, "boolean");
   UTCHARTSMOOTHAREAContainer.setProp("TrendPeriod", "Trendperiod", "", "char");
   UTCHARTSMOOTHAREAContainer.setProp("IncludeSparkline", "Includesparkline", false, "boolean");
   UTCHARTSMOOTHAREAContainer.setProp("IncludeMaxAndMin", "Includemaxandmin", false, "boolean");
   UTCHARTSMOOTHAREAContainer.setProp("ChartType", "Charttype", "SmoothArea", "str");
   UTCHARTSMOOTHAREAContainer.setProp("Title", "Title", "", "str");
   UTCHARTSMOOTHAREAContainer.setProp("PlotSeries", "Plotseries", "InTheSameChart", "str");
   UTCHARTSMOOTHAREAContainer.setProp("ShowValues", "Showvalues", true, "bool");
   UTCHARTSMOOTHAREAContainer.setProp("XAxisLabels", "Xaxislabels", "Horizontally", "str");
   UTCHARTSMOOTHAREAContainer.setProp("XAxisIntersectionAtZero", "Xaxisintersectionatzero", false, "bool");
   UTCHARTSMOOTHAREAContainer.setProp("XAxisTitle", "Xaxistitle", "", "str");
   UTCHARTSMOOTHAREAContainer.setProp("YAxisTitle", "Yaxistitle", "", "str");
   UTCHARTSMOOTHAREAContainer.setProp("Paging", "Paging", false, "boolean");
   UTCHARTSMOOTHAREAContainer.setProp("PageSize", "Pagesize", '', "int");
   UTCHARTSMOOTHAREAContainer.setProp("CurrentPage", "Currentpage", '', "int");
   UTCHARTSMOOTHAREAContainer.setProp("ShowDataLabelsIn", "Showdatalabelsin", "", "char");
   UTCHARTSMOOTHAREAContainer.addV2CFunction('AV15ItemClickData', "vITEMCLICKDATA", 'SetItemClickData');
   UTCHARTSMOOTHAREAContainer.addC2VFunction(function(UC) { UC.ParentObject.AV15ItemClickData=UC.GetItemClickData();gx.fn.setControlValue("vITEMCLICKDATA",UC.ParentObject.AV15ItemClickData); });
   UTCHARTSMOOTHAREAContainer.addV2CFunction('AV16ItemDoubleClickData', "vITEMDOUBLECLICKDATA", 'SetItemDoubleClickData');
   UTCHARTSMOOTHAREAContainer.addC2VFunction(function(UC) { UC.ParentObject.AV16ItemDoubleClickData=UC.GetItemDoubleClickData();gx.fn.setControlValue("vITEMDOUBLECLICKDATA",UC.ParentObject.AV16ItemDoubleClickData); });
   UTCHARTSMOOTHAREAContainer.addV2CFunction('AV17DragAndDropData', "vDRAGANDDROPDATA", 'SetDragAndDropData');
   UTCHARTSMOOTHAREAContainer.addC2VFunction(function(UC) { UC.ParentObject.AV17DragAndDropData=UC.GetDragAndDropData();gx.fn.setControlValue("vDRAGANDDROPDATA",UC.ParentObject.AV17DragAndDropData); });
   UTCHARTSMOOTHAREAContainer.addV2CFunction('AV18FilterChangedData', "vFILTERCHANGEDDATA", 'SetFilterChangedData');
   UTCHARTSMOOTHAREAContainer.addC2VFunction(function(UC) { UC.ParentObject.AV18FilterChangedData=UC.GetFilterChangedData();gx.fn.setControlValue("vFILTERCHANGEDDATA",UC.ParentObject.AV18FilterChangedData); });
   UTCHARTSMOOTHAREAContainer.addV2CFunction('AV19ItemExpandData', "vITEMEXPANDDATA", 'SetItemExpandData');
   UTCHARTSMOOTHAREAContainer.addC2VFunction(function(UC) { UC.ParentObject.AV19ItemExpandData=UC.GetItemExpandData();gx.fn.setControlValue("vITEMEXPANDDATA",UC.ParentObject.AV19ItemExpandData); });
   UTCHARTSMOOTHAREAContainer.addV2CFunction('AV20ItemCollapseData', "vITEMCOLLAPSEDATA", 'SetItemCollapseData');
   UTCHARTSMOOTHAREAContainer.addC2VFunction(function(UC) { UC.ParentObject.AV20ItemCollapseData=UC.GetItemCollapseData();gx.fn.setControlValue("vITEMCOLLAPSEDATA",UC.ParentObject.AV20ItemCollapseData); });
   UTCHARTSMOOTHAREAContainer.setProp("AppSettings", "Appsettings", "", "char");
   UTCHARTSMOOTHAREAContainer.setProp("AvoidAutomaticShow", "Avoidautomaticshow", false, "boolean");
   UTCHARTSMOOTHAREAContainer.setProp("ExecuteShow", "Executeshow", false, "boolean");
   UTCHARTSMOOTHAREAContainer.setProp("ServiceUrl", "Serviceurl", "", "char");
   UTCHARTSMOOTHAREAContainer.setProp("GenType", "Gentype", "", "char");
   UTCHARTSMOOTHAREAContainer.setProp("DesignRenderOutputType", "Designrenderoutputtype", "", "char");
   UTCHARTSMOOTHAREAContainer.setProp("Visible", "Visible", true, "bool");
   UTCHARTSMOOTHAREAContainer.setProp("Gx Control Type", "Gxcontroltype", '', "int");
   UTCHARTSMOOTHAREAContainer.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(UTCHARTSMOOTHAREAContainer);
   this.DVPANEL_TABLECHART1Container = gx.uc.getNew(this, 113, 27, "BootstrapPanel", "DVPANEL_TABLECHART1Container", "Dvpanel_tablechart1", "DVPANEL_TABLECHART1");
   var DVPANEL_TABLECHART1Container = this.DVPANEL_TABLECHART1Container;
   DVPANEL_TABLECHART1Container.setProp("Class", "Class", "", "char");
   DVPANEL_TABLECHART1Container.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_TABLECHART1Container.setProp("Width", "Width", "100%", "str");
   DVPANEL_TABLECHART1Container.setProp("Height", "Height", "100", "str");
   DVPANEL_TABLECHART1Container.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_TABLECHART1Container.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_TABLECHART1Container.setProp("Cls", "Cls", "PanelNoHeader", "str");
   DVPANEL_TABLECHART1Container.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_TABLECHART1Container.setProp("Title", "Title", gx.getMessage( "Task Board"), "str");
   DVPANEL_TABLECHART1Container.setProp("Collapsible", "Collapsible", true, "bool");
   DVPANEL_TABLECHART1Container.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_TABLECHART1Container.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_TABLECHART1Container.setProp("IconPosition", "Iconposition", "right", "str");
   DVPANEL_TABLECHART1Container.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_TABLECHART1Container.setProp("Visible", "Visible", true, "bool");
   DVPANEL_TABLECHART1Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_TABLECHART1Container);
   this.UTCHARTDOUGHNUTContainer = gx.uc.getNew(this, 136, 27, "QueryViewer", "UTCHARTDOUGHNUTContainer", "Utchartdoughnut", "UTCHARTDOUGHNUT");
   var UTCHARTDOUGHNUTContainer = this.UTCHARTDOUGHNUTContainer;
   UTCHARTDOUGHNUTContainer.setProp("Enabled", "Enabled", true, "boolean");
   UTCHARTDOUGHNUTContainer.setProp("ObjectId", "Objectid", "5", "str");
   UTCHARTDOUGHNUTContainer.setProp("ObjectType", "Objecttype", "DataProvider", "str");
   UTCHARTDOUGHNUTContainer.setProp("QueryInfo", "Queryinfo", "", "char");
   UTCHARTDOUGHNUTContainer.setProp("IsExternalQuery", "Isexternalquery", false, "boolean");
   UTCHARTDOUGHNUTContainer.setProp("ExternalQueryResult", "Externalqueryresult", "", "char");
   UTCHARTDOUGHNUTContainer.setProp("ObjectInfo", "Objectinfo", "", "char");
   UTCHARTDOUGHNUTContainer.addV2CFunction('AV13Axes', "vAXES", 'SetAxes');
   UTCHARTDOUGHNUTContainer.addC2VFunction(function(UC) { UC.ParentObject.AV13Axes=UC.GetAxes();gx.fn.setControlValue("vAXES",UC.ParentObject.AV13Axes); });
   UTCHARTDOUGHNUTContainer.setProp("AllowChangeAxesOrder", "Allowchangeaxesorder", false, "bool");
   UTCHARTDOUGHNUTContainer.addV2CFunction('AV14Parameters', "vPARAMETERS", 'SetParameters');
   UTCHARTDOUGHNUTContainer.addC2VFunction(function(UC) { UC.ParentObject.AV14Parameters=UC.GetParameters();gx.fn.setControlValue("vPARAMETERS",UC.ParentObject.AV14Parameters); });
   UTCHARTDOUGHNUTContainer.setProp("ObjectName", "Objectname", "GetHomeSampleNameValueData", "str");
   UTCHARTDOUGHNUTContainer.setProp("Object", "Objectcall", "", "str");
   UTCHARTDOUGHNUTContainer.setProp("Class", "Class", "QueryViewer", "str");
   UTCHARTDOUGHNUTContainer.setProp("ShrinkToFit", "Shrinktofit", false, "boolean");
   UTCHARTDOUGHNUTContainer.setProp("AutoResize", "Autoresize", false, "boolean");
   UTCHARTDOUGHNUTContainer.setProp("AutoResizeType", "Autoresizetype", "", "char");
   UTCHARTDOUGHNUTContainer.setProp("Width", "Width", "300", "str");
   UTCHARTDOUGHNUTContainer.setProp("Height", "Height", "450", "str");
   UTCHARTDOUGHNUTContainer.setProp("Axes Selectors", "Showaxesselectors", "", "char");
   UTCHARTDOUGHNUTContainer.setProp("FontFamily", "Fontfamily", "", "char");
   UTCHARTDOUGHNUTContainer.setProp("FontSize", "Fontsize", '', "int");
   UTCHARTDOUGHNUTContainer.setProp("FontColor", "Fontcolor", '', "int");
   UTCHARTDOUGHNUTContainer.setProp("AutoRefreshGroup", "Autorefreshgroup", "", "str");
   UTCHARTDOUGHNUTContainer.setProp("DisableColumnSort", "Disablecolumnsort", false, "boolean");
   UTCHARTDOUGHNUTContainer.setProp("AllowSelection", "Allowselection", false, "bool");
   UTCHARTDOUGHNUTContainer.setProp("RememberLayout", "Rememberlayout", true, "bool");
   UTCHARTDOUGHNUTContainer.setProp("ExportToXML", "Exporttoxml", true, "bool");
   UTCHARTDOUGHNUTContainer.setProp("ExportToHTML", "Exporttohtml", true, "bool");
   UTCHARTDOUGHNUTContainer.setProp("ExportToXLS", "Exporttoxls", true, "bool");
   UTCHARTDOUGHNUTContainer.setProp("ExportToXLSX", "Exporttoxlsx", true, "bool");
   UTCHARTDOUGHNUTContainer.setProp("ExportToPDF", "Exporttopdf", true, "bool");
   UTCHARTDOUGHNUTContainer.setProp("Type", "Type", "Chart", "str");
   UTCHARTDOUGHNUTContainer.setProp("ShowDataAs", "Showdataas", "", "char");
   UTCHARTDOUGHNUTContainer.setProp("Orientation", "Orientation", "", "char");
   UTCHARTDOUGHNUTContainer.setProp("IncludeTrend", "Includetrend", false, "boolean");
   UTCHARTDOUGHNUTContainer.setProp("TrendPeriod", "Trendperiod", "", "char");
   UTCHARTDOUGHNUTContainer.setProp("IncludeSparkline", "Includesparkline", false, "boolean");
   UTCHARTDOUGHNUTContainer.setProp("IncludeMaxAndMin", "Includemaxandmin", false, "boolean");
   UTCHARTDOUGHNUTContainer.setProp("ChartType", "Charttype", "Doughnut", "str");
   UTCHARTDOUGHNUTContainer.setProp("Title", "Title", "", "str");
   UTCHARTDOUGHNUTContainer.setProp("PlotSeries", "Plotseries", "InTheSameChart", "str");
   UTCHARTDOUGHNUTContainer.setProp("ShowValues", "Showvalues", false, "bool");
   UTCHARTDOUGHNUTContainer.setProp("XAxisLabels", "Xaxislabels", "Horizontally", "str");
   UTCHARTDOUGHNUTContainer.setProp("XAxisIntersectionAtZero", "Xaxisintersectionatzero", false, "bool");
   UTCHARTDOUGHNUTContainer.setProp("XAxisTitle", "Xaxistitle", "", "str");
   UTCHARTDOUGHNUTContainer.setProp("YAxisTitle", "Yaxistitle", "", "str");
   UTCHARTDOUGHNUTContainer.setProp("Paging", "Paging", false, "boolean");
   UTCHARTDOUGHNUTContainer.setProp("PageSize", "Pagesize", '', "int");
   UTCHARTDOUGHNUTContainer.setProp("CurrentPage", "Currentpage", '', "int");
   UTCHARTDOUGHNUTContainer.setProp("ShowDataLabelsIn", "Showdatalabelsin", "", "char");
   UTCHARTDOUGHNUTContainer.addV2CFunction('AV15ItemClickData', "vITEMCLICKDATA", 'SetItemClickData');
   UTCHARTDOUGHNUTContainer.addC2VFunction(function(UC) { UC.ParentObject.AV15ItemClickData=UC.GetItemClickData();gx.fn.setControlValue("vITEMCLICKDATA",UC.ParentObject.AV15ItemClickData); });
   UTCHARTDOUGHNUTContainer.addV2CFunction('AV16ItemDoubleClickData', "vITEMDOUBLECLICKDATA", 'SetItemDoubleClickData');
   UTCHARTDOUGHNUTContainer.addC2VFunction(function(UC) { UC.ParentObject.AV16ItemDoubleClickData=UC.GetItemDoubleClickData();gx.fn.setControlValue("vITEMDOUBLECLICKDATA",UC.ParentObject.AV16ItemDoubleClickData); });
   UTCHARTDOUGHNUTContainer.addV2CFunction('AV17DragAndDropData', "vDRAGANDDROPDATA", 'SetDragAndDropData');
   UTCHARTDOUGHNUTContainer.addC2VFunction(function(UC) { UC.ParentObject.AV17DragAndDropData=UC.GetDragAndDropData();gx.fn.setControlValue("vDRAGANDDROPDATA",UC.ParentObject.AV17DragAndDropData); });
   UTCHARTDOUGHNUTContainer.addV2CFunction('AV18FilterChangedData', "vFILTERCHANGEDDATA", 'SetFilterChangedData');
   UTCHARTDOUGHNUTContainer.addC2VFunction(function(UC) { UC.ParentObject.AV18FilterChangedData=UC.GetFilterChangedData();gx.fn.setControlValue("vFILTERCHANGEDDATA",UC.ParentObject.AV18FilterChangedData); });
   UTCHARTDOUGHNUTContainer.addV2CFunction('AV19ItemExpandData', "vITEMEXPANDDATA", 'SetItemExpandData');
   UTCHARTDOUGHNUTContainer.addC2VFunction(function(UC) { UC.ParentObject.AV19ItemExpandData=UC.GetItemExpandData();gx.fn.setControlValue("vITEMEXPANDDATA",UC.ParentObject.AV19ItemExpandData); });
   UTCHARTDOUGHNUTContainer.addV2CFunction('AV20ItemCollapseData', "vITEMCOLLAPSEDATA", 'SetItemCollapseData');
   UTCHARTDOUGHNUTContainer.addC2VFunction(function(UC) { UC.ParentObject.AV20ItemCollapseData=UC.GetItemCollapseData();gx.fn.setControlValue("vITEMCOLLAPSEDATA",UC.ParentObject.AV20ItemCollapseData); });
   UTCHARTDOUGHNUTContainer.setProp("AppSettings", "Appsettings", "", "char");
   UTCHARTDOUGHNUTContainer.setProp("AvoidAutomaticShow", "Avoidautomaticshow", false, "boolean");
   UTCHARTDOUGHNUTContainer.setProp("ExecuteShow", "Executeshow", false, "boolean");
   UTCHARTDOUGHNUTContainer.setProp("ServiceUrl", "Serviceurl", "", "char");
   UTCHARTDOUGHNUTContainer.setProp("GenType", "Gentype", "", "char");
   UTCHARTDOUGHNUTContainer.setProp("DesignRenderOutputType", "Designrenderoutputtype", "", "char");
   UTCHARTDOUGHNUTContainer.setProp("Visible", "Visible", true, "bool");
   UTCHARTDOUGHNUTContainer.setProp("Gx Control Type", "Gxcontroltype", '', "int");
   UTCHARTDOUGHNUTContainer.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(UTCHARTDOUGHNUTContainer);
   this.DVPANEL_TABLECHART3Container = gx.uc.getNew(this, 129, 27, "BootstrapPanel", "DVPANEL_TABLECHART3Container", "Dvpanel_tablechart3", "DVPANEL_TABLECHART3");
   var DVPANEL_TABLECHART3Container = this.DVPANEL_TABLECHART3Container;
   DVPANEL_TABLECHART3Container.setProp("Class", "Class", "", "char");
   DVPANEL_TABLECHART3Container.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_TABLECHART3Container.setProp("Width", "Width", "100%", "str");
   DVPANEL_TABLECHART3Container.setProp("Height", "Height", "100", "str");
   DVPANEL_TABLECHART3Container.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_TABLECHART3Container.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_TABLECHART3Container.setProp("Cls", "Cls", "PanelCard_Warning", "str");
   DVPANEL_TABLECHART3Container.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_TABLECHART3Container.setProp("Title", "Title", gx.getMessage( "Orders"), "str");
   DVPANEL_TABLECHART3Container.setProp("Collapsible", "Collapsible", false, "bool");
   DVPANEL_TABLECHART3Container.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_TABLECHART3Container.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_TABLECHART3Container.setProp("IconPosition", "Iconposition", "right", "str");
   DVPANEL_TABLECHART3Container.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_TABLECHART3Container.setProp("Visible", "Visible", true, "bool");
   DVPANEL_TABLECHART3Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_TABLECHART3Container);
   this.UTCHARTSMOOTHLINEContainer = gx.uc.getNew(this, 146, 27, "QueryViewer", "UTCHARTSMOOTHLINEContainer", "Utchartsmoothline", "UTCHARTSMOOTHLINE");
   var UTCHARTSMOOTHLINEContainer = this.UTCHARTSMOOTHLINEContainer;
   UTCHARTSMOOTHLINEContainer.setProp("Enabled", "Enabled", true, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("ObjectId", "Objectid", "1", "str");
   UTCHARTSMOOTHLINEContainer.setProp("ObjectType", "Objecttype", "DataProvider", "str");
   UTCHARTSMOOTHLINEContainer.setProp("QueryInfo", "Queryinfo", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("IsExternalQuery", "Isexternalquery", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("ExternalQueryResult", "Externalqueryresult", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("ObjectInfo", "Objectinfo", "", "char");
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV13Axes', "vAXES", 'SetAxes');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV13Axes=UC.GetAxes();gx.fn.setControlValue("vAXES",UC.ParentObject.AV13Axes); });
   UTCHARTSMOOTHLINEContainer.setProp("AllowChangeAxesOrder", "Allowchangeaxesorder", false, "bool");
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV14Parameters', "vPARAMETERS", 'SetParameters');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV14Parameters=UC.GetParameters();gx.fn.setControlValue("vPARAMETERS",UC.ParentObject.AV14Parameters); });
   UTCHARTSMOOTHLINEContainer.setProp("ObjectName", "Objectname", "GetHomeSampleData", "str");
   UTCHARTSMOOTHLINEContainer.setProp("Object", "Objectcall", "", "str");
   UTCHARTSMOOTHLINEContainer.setProp("Class", "Class", "QueryViewer", "str");
   UTCHARTSMOOTHLINEContainer.setProp("ShrinkToFit", "Shrinktofit", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("AutoResize", "Autoresize", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("AutoResizeType", "Autoresizetype", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("Width", "Width", "100%", "str");
   UTCHARTSMOOTHLINEContainer.setProp("Height", "Height", "450", "str");
   UTCHARTSMOOTHLINEContainer.setProp("Axes Selectors", "Showaxesselectors", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("FontFamily", "Fontfamily", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("FontSize", "Fontsize", '', "int");
   UTCHARTSMOOTHLINEContainer.setProp("FontColor", "Fontcolor", '', "int");
   UTCHARTSMOOTHLINEContainer.setProp("AutoRefreshGroup", "Autorefreshgroup", "", "str");
   UTCHARTSMOOTHLINEContainer.setProp("DisableColumnSort", "Disablecolumnsort", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("AllowSelection", "Allowselection", false, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("RememberLayout", "Rememberlayout", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("ExportToXML", "Exporttoxml", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("ExportToHTML", "Exporttohtml", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("ExportToXLS", "Exporttoxls", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("ExportToXLSX", "Exporttoxlsx", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("ExportToPDF", "Exporttopdf", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("Type", "Type", "Chart", "str");
   UTCHARTSMOOTHLINEContainer.setProp("ShowDataAs", "Showdataas", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("Orientation", "Orientation", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("IncludeTrend", "Includetrend", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("TrendPeriod", "Trendperiod", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("IncludeSparkline", "Includesparkline", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("IncludeMaxAndMin", "Includemaxandmin", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("ChartType", "Charttype", "SmoothLine", "str");
   UTCHARTSMOOTHLINEContainer.setProp("Title", "Title", "", "str");
   UTCHARTSMOOTHLINEContainer.setProp("PlotSeries", "Plotseries", "InTheSameChart", "str");
   UTCHARTSMOOTHLINEContainer.setProp("ShowValues", "Showvalues", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("XAxisLabels", "Xaxislabels", "Horizontally", "str");
   UTCHARTSMOOTHLINEContainer.setProp("XAxisIntersectionAtZero", "Xaxisintersectionatzero", false, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("XAxisTitle", "Xaxistitle", "", "str");
   UTCHARTSMOOTHLINEContainer.setProp("YAxisTitle", "Yaxistitle", "", "str");
   UTCHARTSMOOTHLINEContainer.setProp("Paging", "Paging", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("PageSize", "Pagesize", '', "int");
   UTCHARTSMOOTHLINEContainer.setProp("CurrentPage", "Currentpage", '', "int");
   UTCHARTSMOOTHLINEContainer.setProp("ShowDataLabelsIn", "Showdatalabelsin", "", "char");
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV15ItemClickData', "vITEMCLICKDATA", 'SetItemClickData');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV15ItemClickData=UC.GetItemClickData();gx.fn.setControlValue("vITEMCLICKDATA",UC.ParentObject.AV15ItemClickData); });
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV16ItemDoubleClickData', "vITEMDOUBLECLICKDATA", 'SetItemDoubleClickData');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV16ItemDoubleClickData=UC.GetItemDoubleClickData();gx.fn.setControlValue("vITEMDOUBLECLICKDATA",UC.ParentObject.AV16ItemDoubleClickData); });
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV17DragAndDropData', "vDRAGANDDROPDATA", 'SetDragAndDropData');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV17DragAndDropData=UC.GetDragAndDropData();gx.fn.setControlValue("vDRAGANDDROPDATA",UC.ParentObject.AV17DragAndDropData); });
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV18FilterChangedData', "vFILTERCHANGEDDATA", 'SetFilterChangedData');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV18FilterChangedData=UC.GetFilterChangedData();gx.fn.setControlValue("vFILTERCHANGEDDATA",UC.ParentObject.AV18FilterChangedData); });
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV19ItemExpandData', "vITEMEXPANDDATA", 'SetItemExpandData');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV19ItemExpandData=UC.GetItemExpandData();gx.fn.setControlValue("vITEMEXPANDDATA",UC.ParentObject.AV19ItemExpandData); });
   UTCHARTSMOOTHLINEContainer.addV2CFunction('AV20ItemCollapseData', "vITEMCOLLAPSEDATA", 'SetItemCollapseData');
   UTCHARTSMOOTHLINEContainer.addC2VFunction(function(UC) { UC.ParentObject.AV20ItemCollapseData=UC.GetItemCollapseData();gx.fn.setControlValue("vITEMCOLLAPSEDATA",UC.ParentObject.AV20ItemCollapseData); });
   UTCHARTSMOOTHLINEContainer.setProp("AppSettings", "Appsettings", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("AvoidAutomaticShow", "Avoidautomaticshow", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("ExecuteShow", "Executeshow", false, "boolean");
   UTCHARTSMOOTHLINEContainer.setProp("ServiceUrl", "Serviceurl", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("GenType", "Gentype", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("DesignRenderOutputType", "Designrenderoutputtype", "", "char");
   UTCHARTSMOOTHLINEContainer.setProp("Visible", "Visible", true, "bool");
   UTCHARTSMOOTHLINEContainer.setProp("Gx Control Type", "Gxcontroltype", '', "int");
   UTCHARTSMOOTHLINEContainer.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(UTCHARTSMOOTHLINEContainer);
   this.DVPANEL_TABLECHART4Container = gx.uc.getNew(this, 139, 27, "BootstrapPanel", "DVPANEL_TABLECHART4Container", "Dvpanel_tablechart4", "DVPANEL_TABLECHART4");
   var DVPANEL_TABLECHART4Container = this.DVPANEL_TABLECHART4Container;
   DVPANEL_TABLECHART4Container.setProp("Class", "Class", "", "char");
   DVPANEL_TABLECHART4Container.setProp("Enabled", "Enabled", true, "boolean");
   DVPANEL_TABLECHART4Container.setProp("Width", "Width", "100%", "str");
   DVPANEL_TABLECHART4Container.setProp("Height", "Height", "100", "str");
   DVPANEL_TABLECHART4Container.setProp("AutoWidth", "Autowidth", false, "bool");
   DVPANEL_TABLECHART4Container.setProp("AutoHeight", "Autoheight", true, "bool");
   DVPANEL_TABLECHART4Container.setProp("Cls", "Cls", "PanelCard_BaseColor", "str");
   DVPANEL_TABLECHART4Container.setProp("ShowHeader", "Showheader", true, "bool");
   DVPANEL_TABLECHART4Container.setProp("Title", "Title", gx.getMessage( "Task Board"), "str");
   DVPANEL_TABLECHART4Container.setProp("Collapsible", "Collapsible", false, "bool");
   DVPANEL_TABLECHART4Container.setProp("Collapsed", "Collapsed", false, "bool");
   DVPANEL_TABLECHART4Container.setProp("ShowCollapseIcon", "Showcollapseicon", false, "bool");
   DVPANEL_TABLECHART4Container.setProp("IconPosition", "Iconposition", "right", "str");
   DVPANEL_TABLECHART4Container.setProp("AutoScroll", "Autoscroll", false, "bool");
   DVPANEL_TABLECHART4Container.setProp("Visible", "Visible", true, "bool");
   DVPANEL_TABLECHART4Container.setC2ShowFunction(function(UC) { UC.show(); });
   this.setUserControl(DVPANEL_TABLECHART4Container);
   GXValidFnc[2]={ id: 2, fld:"",grid:0};
   GXValidFnc[3]={ id: 3, fld:"LAYOUTMAINTABLE",grid:0};
   GXValidFnc[4]={ id: 4, fld:"",grid:0};
   GXValidFnc[5]={ id: 5, fld:"",grid:0};
   GXValidFnc[6]={ id: 6, fld:"TABLEMAIN",grid:0};
   GXValidFnc[7]={ id: 7, fld:"",grid:0};
   GXValidFnc[8]={ id: 8, fld:"",grid:0};
   GXValidFnc[9]={ id: 9, fld:"TABLECARDS",grid:0};
   GXValidFnc[10]={ id: 10, fld:"",grid:0};
   GXValidFnc[11]={ id: 11, fld:"",grid:0};
   GXValidFnc[12]={ id: 12, fld:"HTML_DVPANEL_CARD1",grid:0};
   GXValidFnc[15]={ id: 15, fld:"LAYOUT_CARD1",grid:0};
   GXValidFnc[16]={ id: 16, fld:"",grid:0};
   GXValidFnc[17]={ id: 17, fld:"CARD1",grid:0};
   GXValidFnc[18]={ id: 18, fld:"",grid:0};
   GXValidFnc[19]={ id: 19, fld:"",grid:0};
   GXValidFnc[20]={ id: 20, fld:"CARD1CONTENT",grid:0};
   GXValidFnc[21]={ id: 21, fld:"",grid:0};
   GXValidFnc[22]={ id: 22, fld:"",grid:0};
   GXValidFnc[23]={ id: 23, fld:"DESCRIPTIONCARD1", format:0,grid:0};
   GXValidFnc[24]={ id: 24, fld:"",grid:0};
   GXValidFnc[25]={ id: 25, fld:"",grid:0};
   GXValidFnc[26]={ id: 26, fld:"",grid:0};
   GXValidFnc[27]={ id:27 ,lvl:0,type:"int",len:8,dec:0,sign:false,pic:"ZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vVALUECARD1",gxz:"ZV12ValueCard1",gxold:"OV12ValueCard1",gxvar:"AV12ValueCard1",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV12ValueCard1=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV12ValueCard1=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vVALUECARD1",gx.O.AV12ValueCard1,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.AV12ValueCard1=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vVALUECARD1",gx.thousandSeparator)},nac:gx.falseFn};
   this.declareDomainHdlr( 27 , function() {
   });
   GXValidFnc[28]={ id: 28, fld:"",grid:0};
   GXValidFnc[29]={ id: 29, fld:"",grid:0};
   GXValidFnc[30]={ id: 30, fld:"MOREINFOCARD1",grid:0};
   GXValidFnc[33]={ id: 33, fld:"MOREINFOICONCARD1", format:2,grid:0};
   GXValidFnc[35]={ id: 35, fld:"MOREINFOCARD1CAPTION", format:0,grid:0};
   GXValidFnc[36]={ id: 36, fld:"",grid:0};
   GXValidFnc[37]={ id: 37, fld:"HTML_DVPANEL_CARD2",grid:0};
   GXValidFnc[40]={ id: 40, fld:"LAYOUT_CARD2",grid:0};
   GXValidFnc[41]={ id: 41, fld:"",grid:0};
   GXValidFnc[42]={ id: 42, fld:"CARD2",grid:0};
   GXValidFnc[43]={ id: 43, fld:"",grid:0};
   GXValidFnc[44]={ id: 44, fld:"",grid:0};
   GXValidFnc[45]={ id: 45, fld:"UNNAMEDTABLE3",grid:0};
   GXValidFnc[46]={ id: 46, fld:"",grid:0};
   GXValidFnc[47]={ id: 47, fld:"",grid:0};
   GXValidFnc[48]={ id: 48, fld:"DESCRIPTIONCARD2", format:0,grid:0};
   GXValidFnc[49]={ id: 49, fld:"",grid:0};
   GXValidFnc[50]={ id: 50, fld:"",grid:0};
   GXValidFnc[51]={ id: 51, fld:"",grid:0};
   GXValidFnc[52]={ id:52 ,lvl:0,type:"int",len:8,dec:0,sign:false,pic:"$ZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vVALUECARD2",gxz:"ZV11ValueCard2",gxold:"OV11ValueCard2",gxvar:"AV11ValueCard2",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV11ValueCard2=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV11ValueCard2=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vVALUECARD2",gx.O.AV11ValueCard2,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.AV11ValueCard2=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vVALUECARD2",gx.thousandSeparator)},nac:gx.falseFn};
   this.declareDomainHdlr( 52 , function() {
   });
   GXValidFnc[53]={ id: 53, fld:"",grid:0};
   GXValidFnc[54]={ id: 54, fld:"",grid:0};
   GXValidFnc[55]={ id: 55, fld:"MOREINFOCARD2",grid:0};
   GXValidFnc[58]={ id: 58, fld:"MOREINFOICONCARD2", format:2,grid:0};
   GXValidFnc[60]={ id: 60, fld:"MOREINFOCARD2CAPTION", format:0,grid:0};
   GXValidFnc[61]={ id: 61, fld:"",grid:0};
   GXValidFnc[62]={ id: 62, fld:"HTML_DVPANEL_CARD3",grid:0};
   GXValidFnc[65]={ id: 65, fld:"LAYOUT_CARD3",grid:0};
   GXValidFnc[66]={ id: 66, fld:"",grid:0};
   GXValidFnc[67]={ id: 67, fld:"CARD3",grid:0};
   GXValidFnc[68]={ id: 68, fld:"",grid:0};
   GXValidFnc[69]={ id: 69, fld:"",grid:0};
   GXValidFnc[70]={ id: 70, fld:"UNNAMEDTABLE2",grid:0};
   GXValidFnc[71]={ id: 71, fld:"",grid:0};
   GXValidFnc[72]={ id: 72, fld:"",grid:0};
   GXValidFnc[73]={ id: 73, fld:"DESCRIPTIONCARD3", format:0,grid:0};
   GXValidFnc[74]={ id: 74, fld:"",grid:0};
   GXValidFnc[75]={ id: 75, fld:"",grid:0};
   GXValidFnc[76]={ id: 76, fld:"",grid:0};
   GXValidFnc[77]={ id:77 ,lvl:0,type:"svchar",len:40,dec:0,sign:false,ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vVALUECARD3",gxz:"ZV10ValueCard3",gxold:"OV10ValueCard3",gxvar:"AV10ValueCard3",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV10ValueCard3=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV10ValueCard3=Value},v2c:function(){gx.fn.setControlValue("vVALUECARD3",gx.O.AV10ValueCard3,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.AV10ValueCard3=this.val()},val:function(){return gx.fn.getControlValue("vVALUECARD3")},nac:gx.falseFn};
   this.declareDomainHdlr( 77 , function() {
   });
   GXValidFnc[78]={ id: 78, fld:"",grid:0};
   GXValidFnc[79]={ id: 79, fld:"",grid:0};
   GXValidFnc[80]={ id: 80, fld:"MOREINFOCARD3",grid:0};
   GXValidFnc[83]={ id: 83, fld:"MOREINFOICONCARD3", format:2,grid:0};
   GXValidFnc[85]={ id: 85, fld:"MOREINFOCARD3CAPTION", format:0,grid:0};
   GXValidFnc[86]={ id: 86, fld:"",grid:0};
   GXValidFnc[87]={ id: 87, fld:"HTML_DVPANEL_CARD4",grid:0};
   GXValidFnc[90]={ id: 90, fld:"LAYOUT_CARD4",grid:0};
   GXValidFnc[91]={ id: 91, fld:"",grid:0};
   GXValidFnc[92]={ id: 92, fld:"CARD4",grid:0};
   GXValidFnc[93]={ id: 93, fld:"",grid:0};
   GXValidFnc[94]={ id: 94, fld:"",grid:0};
   GXValidFnc[95]={ id: 95, fld:"UNNAMEDTABLE1",grid:0};
   GXValidFnc[96]={ id: 96, fld:"",grid:0};
   GXValidFnc[97]={ id: 97, fld:"",grid:0};
   GXValidFnc[98]={ id: 98, fld:"DESCRIPTIONCARD4", format:0,grid:0};
   GXValidFnc[99]={ id: 99, fld:"",grid:0};
   GXValidFnc[100]={ id: 100, fld:"",grid:0};
   GXValidFnc[101]={ id: 101, fld:"",grid:0};
   GXValidFnc[102]={ id:102 ,lvl:0,type:"int",len:8,dec:0,sign:false,pic:"ZZ,ZZZ,ZZ9",ro:0,grid:0,gxgrid:null,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"vVALUECARD4",gxz:"ZV9ValueCard4",gxold:"OV9ValueCard4",gxvar:"AV9ValueCard4",ucs:[],op:[],ip:[],
						nacdep:[],ctrltype:"edit",v2v:function(Value){if(Value!==undefined)gx.O.AV9ValueCard4=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV9ValueCard4=gx.num.intval(Value)},v2c:function(){gx.fn.setControlValue("vVALUECARD4",gx.O.AV9ValueCard4,0);if (typeof(this.dom_hdl) == 'function') this.dom_hdl.call(gx.O);},c2v:function(){if(this.val()!==undefined)gx.O.AV9ValueCard4=gx.num.intval(this.val())},val:function(){return gx.fn.getIntegerValue("vVALUECARD4",gx.thousandSeparator)},nac:gx.falseFn};
   this.declareDomainHdlr( 102 , function() {
   });
   GXValidFnc[103]={ id: 103, fld:"",grid:0};
   GXValidFnc[104]={ id: 104, fld:"",grid:0};
   GXValidFnc[105]={ id: 105, fld:"MOREINFOCARD4",grid:0};
   GXValidFnc[108]={ id: 108, fld:"MOREINFOICONCARD4", format:2,grid:0};
   GXValidFnc[110]={ id: 110, fld:"MOREINFOCARD4CAPTION", format:0,grid:0};
   GXValidFnc[111]={ id: 111, fld:"",grid:0};
   GXValidFnc[112]={ id: 112, fld:"HTML_DVPANEL_TABLECHART1",grid:0};
   GXValidFnc[115]={ id: 115, fld:"LAYOUT_TABLECHART1",grid:0};
   GXValidFnc[116]={ id: 116, fld:"",grid:0};
   GXValidFnc[117]={ id: 117, fld:"TABLECHART1",grid:0};
   GXValidFnc[118]={ id: 118, fld:"",grid:0};
   GXValidFnc[119]={ id: 119, fld:"",grid:0};
   GXValidFnc[121]={ id: 121, fld:"",grid:0};
   GXValidFnc[123]={ id:123 ,lvl:2,type:"svchar",len:40,dec:0,sign:false,ro:1,isacc:0,grid:122,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"HOMESAMPLEDATA__PRODUCTNAME",gxz:"ZV26GXV2",gxold:"OV26GXV2",gxvar:"GXV2",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',autoCorrect:"1",v2v:function(Value){if(Value!==undefined)gx.O.GXV2=Value},v2z:function(Value){if(Value!==undefined)gx.O.ZV26GXV2=Value},v2c:function(row){gx.fn.setGridControlValue("HOMESAMPLEDATA__PRODUCTNAME",row || gx.fn.currentGridRowImpl(122),gx.O.GXV2,0)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV2=this.val(row)},val:function(row){return gx.fn.getGridControlValue("HOMESAMPLEDATA__PRODUCTNAME",row || gx.fn.currentGridRowImpl(122))},nac:gx.falseFn};
   GXValidFnc[124]={ id:124 ,lvl:2,type:"decimal",len:8,dec:1,sign:false,pic:"$ ZZZ,ZZ9.9",ro:1,isacc:0,grid:122,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"HOMESAMPLEDATA__PRODUCTPRICE",gxz:"ZV27GXV3",gxold:"OV27GXV3",gxvar:"GXV3",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"edit",inputType:'text',v2v:function(Value){if(Value!==undefined)gx.O.GXV3=gx.fn.toDecimalValue(Value,',','.')},v2z:function(Value){if(Value!==undefined)gx.O.ZV27GXV3=gx.fn.toDecimalValue(Value,gx.thousandSeparator,gx.decimalPoint)},v2c:function(row){gx.fn.setGridDecimalValue("HOMESAMPLEDATA__PRODUCTPRICE",row || gx.fn.currentGridRowImpl(122),gx.O.GXV3,1,gx.decimalPoint)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV3=this.val(row)},val:function(row){return gx.fn.getGridDecimalValue("HOMESAMPLEDATA__PRODUCTPRICE",row || gx.fn.currentGridRowImpl(122),gx.thousandSeparator,gx.decimalPoint)},nac:gx.falseFn};
   GXValidFnc[125]={ id:125 ,lvl:2,type:"int",len:1,dec:0,sign:false,pic:"9",ro:1,isacc:0,grid:122,gxgrid:this.GridContainer,fnc:null,isvalid:null,evt_cvc:null,evt_cvcing:null,rgrid:[],fld:"HOMESAMPLEDATA__PRODUCTSTATUS",gxz:"ZV28GXV4",gxold:"OV28GXV4",gxvar:"GXV4",ucs:[],op:[],ip:[],nacdep:[],ctrltype:"combo",inputType:'number',v2v:function(Value){if(Value!==undefined)gx.O.GXV4=gx.num.intval(Value)},v2z:function(Value){if(Value!==undefined)gx.O.ZV28GXV4=gx.num.intval(Value)},v2c:function(row){gx.fn.setGridComboBoxValue("HOMESAMPLEDATA__PRODUCTSTATUS",row || gx.fn.currentGridRowImpl(122),gx.O.GXV4)},c2v:function(row){if(this.val(row)!==undefined)gx.O.GXV4=gx.num.intval(this.val(row))},val:function(row){return gx.fn.getGridIntegerValue("HOMESAMPLEDATA__PRODUCTSTATUS",row || gx.fn.currentGridRowImpl(122),gx.thousandSeparator)},nac:gx.falseFn};
   GXValidFnc[126]={ id: 126, fld:"",grid:0};
   GXValidFnc[127]={ id: 127, fld:"",grid:0};
   GXValidFnc[128]={ id: 128, fld:"HTML_DVPANEL_TABLECHART3",grid:0};
   GXValidFnc[131]={ id: 131, fld:"LAYOUT_TABLECHART3",grid:0};
   GXValidFnc[132]={ id: 132, fld:"",grid:0};
   GXValidFnc[133]={ id: 133, fld:"TABLECHART3",grid:0};
   GXValidFnc[134]={ id: 134, fld:"",grid:0};
   GXValidFnc[135]={ id: 135, fld:"",grid:0};
   GXValidFnc[137]={ id: 137, fld:"",grid:0};
   GXValidFnc[138]={ id: 138, fld:"HTML_DVPANEL_TABLECHART4",grid:0};
   GXValidFnc[141]={ id: 141, fld:"LAYOUT_TABLECHART4",grid:0};
   GXValidFnc[142]={ id: 142, fld:"",grid:0};
   GXValidFnc[143]={ id: 143, fld:"TABLECHART4",grid:0};
   GXValidFnc[144]={ id: 144, fld:"",grid:0};
   GXValidFnc[145]={ id: 145, fld:"",grid:0};
   this.AV12ValueCard1 = 0 ;
   this.ZV12ValueCard1 = 0 ;
   this.OV12ValueCard1 = 0 ;
   this.AV11ValueCard2 = 0 ;
   this.ZV11ValueCard2 = 0 ;
   this.OV11ValueCard2 = 0 ;
   this.AV10ValueCard3 = "" ;
   this.ZV10ValueCard3 = "" ;
   this.OV10ValueCard3 = "" ;
   this.AV9ValueCard4 = 0 ;
   this.ZV9ValueCard4 = 0 ;
   this.OV9ValueCard4 = 0 ;
   this.ZV26GXV2 = "" ;
   this.OV26GXV2 = "" ;
   this.ZV27GXV3 = 0 ;
   this.OV27GXV3 = 0 ;
   this.ZV28GXV4 = 0 ;
   this.OV28GXV4 = 0 ;
   this.AV12ValueCard1 = 0 ;
   this.AV11ValueCard2 = 0 ;
   this.AV10ValueCard3 = "" ;
   this.AV9ValueCard4 = 0 ;
   this.AV13Axes = [ ] ;
   this.GXV2 = "" ;
   this.GXV3 = 0 ;
   this.GXV4 = 0 ;
   this.AV8HomeSampleData = [ ] ;
   this.Events = {"e13082_client": ["ENTER", true] ,"e14082_client": ["CANCEL", true]};
   this.EvtParms["REFRESH"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV8HomeSampleData',fld:'vHOMESAMPLEDATA',grid:122,pic:'',hsh:true},{av:'nRC_GXsfl_122',ctrl:'GRID',prop:'GridRC'}],[]];
   this.EvtParms["START"] = [[{av:'AV8HomeSampleData',fld:'vHOMESAMPLEDATA',grid:122,pic:'',hsh:true},{av:'GRID_nFirstRecordOnPage'},{av:'nRC_GXsfl_122',ctrl:'GRID',prop:'GridRC'},{av:'GRID_nEOF'},{av:'subGrid_Rows'}],[{av:'gx.fn.getCtrlProperty("TABLECHART4","Height")',ctrl:'TABLECHART4',prop:'Height'},{av:'gx.fn.getCtrlProperty("TABLECHART3","Height")',ctrl:'TABLECHART3',prop:'Height'},{av:'gx.fn.getCtrlProperty("TABLECHART1","Height")',ctrl:'TABLECHART1',prop:'Height'},{ctrl:'GRID',prop:'Rows'},{av:'AV12ValueCard1',fld:'vVALUECARD1',pic:'ZZ,ZZZ,ZZ9'},{av:'AV11ValueCard2',fld:'vVALUECARD2',pic:'$ZZ,ZZZ,ZZ9'},{av:'AV10ValueCard3',fld:'vVALUECARD3',pic:''},{av:'AV9ValueCard4',fld:'vVALUECARD4',pic:'ZZ,ZZZ,ZZ9'},{av:'AV8HomeSampleData',fld:'vHOMESAMPLEDATA',grid:122,pic:'',hsh:true},{av:'GRID_nFirstRecordOnPage'},{av:'nRC_GXsfl_122',ctrl:'GRID',prop:'GridRC'}]];
   this.EvtParms["GRID.LOAD"] = [[{av:'AV8HomeSampleData',fld:'vHOMESAMPLEDATA',grid:122,pic:'',hsh:true},{av:'GRID_nFirstRecordOnPage'},{av:'nRC_GXsfl_122',ctrl:'GRID',prop:'GridRC'}],[{ctrl:'HOMESAMPLEDATA__PRODUCTSTATUS',prop:'Columnclass'}]];
   this.EvtParms["GRID_FIRSTPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV8HomeSampleData',fld:'vHOMESAMPLEDATA',grid:122,pic:'',hsh:true},{av:'nRC_GXsfl_122',ctrl:'GRID',prop:'GridRC'}],[]];
   this.EvtParms["GRID_PREVPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV8HomeSampleData',fld:'vHOMESAMPLEDATA',grid:122,pic:'',hsh:true},{av:'nRC_GXsfl_122',ctrl:'GRID',prop:'GridRC'}],[]];
   this.EvtParms["GRID_NEXTPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV8HomeSampleData',fld:'vHOMESAMPLEDATA',grid:122,pic:'',hsh:true},{av:'nRC_GXsfl_122',ctrl:'GRID',prop:'GridRC'}],[]];
   this.EvtParms["GRID_LASTPAGE"] = [[{av:'GRID_nFirstRecordOnPage'},{av:'GRID_nEOF'},{ctrl:'GRID',prop:'Rows'},{av:'AV8HomeSampleData',fld:'vHOMESAMPLEDATA',grid:122,pic:'',hsh:true},{av:'nRC_GXsfl_122',ctrl:'GRID',prop:'GridRC'}],[]];
   this.setVCMap("AV8HomeSampleData", "vHOMESAMPLEDATA", 0, "CollWWPBaseObjects\HomeSampleData.HomeSampleDataItem", 0, 0);
   this.setVCMap("AV8HomeSampleData", "vHOMESAMPLEDATA", 0, "CollWWPBaseObjects\HomeSampleData.HomeSampleDataItem", 0, 0);
   this.setVCMap("AV8HomeSampleData", "vHOMESAMPLEDATA", 0, "CollWWPBaseObjects\HomeSampleData.HomeSampleDataItem", 0, 0);
   GridContainer.addRefreshingVar({rfrVar:"AV8HomeSampleData"});
   GridContainer.addRefreshingParm({rfrVar:"AV8HomeSampleData"});
   this.addGridBCProperty("Homesampledata", ["ProductName"], this.GXValidFnc[123], "AV8HomeSampleData");
   this.addGridBCProperty("Homesampledata", ["ProductPrice"], this.GXValidFnc[124], "AV8HomeSampleData");
   this.addGridBCProperty("Homesampledata", ["ProductStatus"], this.GXValidFnc[125], "AV8HomeSampleData");
   this.Initialize( );
});
gx.wi( function() { gx.createParentObj(wwpbaseobjects.home);});
